name: Run Integration Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # To read the repository contents (for `actions/checkout`)
      id-token: write  # To use OIDC for accessing resources (if needed)
      actions: read  # Allow the use of actions like `actions/cache`

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache virtual environment
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv  # Cache the virtual environment
          key: ${{ runner.os }}-venv-${{ hashFiles('test/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-            

      - name: Create virtual environment
        if: steps.cache-venv.outputs.cache-hit != 'true'  # Only create if cache is missing
        run: python -m venv .venv

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r test/requirements.txt            

      - name: Get AWS Permissions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/count-db-run-integration-tests
          aws-region: us-east-1

      - name: Run integration tests
        run: |
          source .venv/bin/activate          
          PYTHONPATH=src python -m pytest --color=yes --log-cli-level=INFO --durations=0 test/integration_tests.py
